### ISSUE TITLE
Don't put the virtual env in git

### ISSUE THREAD

**Issue by ibebrett** [tgoldenberg/nlp#1]
The bin, lib, include... folders are part of a virtual env that is setup for your computer. You don't want to include them in the git repo. If you look at say the activate script in bin, you will see it references setting the python path to your desktop/nlp (or whatever the path is, too laze to check). So I would remove those, and add like a gitignore for those files.

**Comment by tgoldenberg** [comment]
@ibebrett 

Cool, thanks!
